{
	"name": "Update production files",
	"on": {
		"schedule": [{"cron": "14 */6 * * *"}],
		"push": {
			"branches": ["master"],
			"paths": [".github/workflows/update.yml"],
		},
    "workflow_dispatch": {},
	},
	"permissions": {
  	contents: write
	},
	"jobs": {
		"update": {
			"name": "Build and update",
			"timeout-minutes": 5,
			"runs-on": "ubuntu-latest",
			"steps": [
				{
					"name": "Print environment",
					"run": "printenv && pwd",
				},
				{
					"name": "Print Go environment",
					"run": "go version && go env",
				},
				{
					"name": "Checkout executable repository",
					"uses": "actions/checkout@v2",
					"with": {
						"repository": "setup-rbxcdn2/build-archive",
						"fetch-depth": 1,
						"ref": "master",
					},
				},
				{
					"name": "Generate module",
					"run": "
						go mod tidy -v
					",
				},
				{
					"name": "Get dependencies",
					"run": "
						go get -v -d ./...
					",
				},
				{
					"name": "Compile executable",
					"run": "
						cd tools/update &&
						go build -v .
					",
				},
				{
					"name": "Run updater",
					"run": "
						cd tools/update &&
						./update -config config.json
					",
				},
				{
					"name": "Commit and push",
					"env": {
						"ACCESS_TOKEN": "${{ secrets.ACCESS_TOKEN }}",
					},
					"run": "
						git config user.email 'updater@build-archive' &&
						git config user.name 'Updater' &&
						git add data/production &&
						git commit -m 'Update production files.' &&
						git push origin master ||
						true
					",
				},
				{
					"name": "Dispatch to ref",
					"run": "curl -L -X POST -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer ${{ secrets.DISPATCH_TOKEN }}' -H 'X-GitHub-Api-Version: 2026-03-10' https://api.github.com/repos/setup-rbxcdn2/ref/actions/workflows/deploy.yml/dispatches -d '{\"ref\":\"deploy\"}'"
				}
			],
		},
	},
}
